export const SELECT_PLAYGROUND = 'SELECT_PLAYGROUND';
export const RECEIVE_PLAYGROUNDS = 'RECEIVE_PLAYGROUNDS';
export const SELECT_EQUIPMENT = 'SELECT_EQUIPMENT';
export const RECEIVE_EQUIPMENTS = 'RECEIVE_EQUIPMENTS';
export const LOAD_ENTITIES = 'LOAD_ENTITIES';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CREATE_PLAYGROUND = 'CREATE_PLAYGROUND';
export const REMOVE_PLAYGROUND = 'REMOVE_PLAYGROUND';
