export const SELECT_PLAYGROUND = 'SELECT_PLAYGROUND';
export const RECEIVE_PLAYGROUNDS = 'RECEIVE_PLAYGROUNDS';
export const LOAD_ENTITIES = 'LOAD_ENTITIES';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
// export const SHOW_NOTIFICATION_SUCCESS = 'SHOW_NOTIFICATION_SUCCESS';
export const REMOVE_PLAYGROUND = 'REMOVE_PLAYGROUND';
